/**
 * Episode byte storage.
 *
 * Stands in for the content-addressed storage of product-spec §10.2 until a
 * provider is picked — the design keeps this behind one interface precisely so
 * that choice can wait. Files land under .data/episodes/<episode_id>/ where
 * they can be inspected, played and fed to the trainer without a gateway.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

export interface StoredStream {
  kind: string;
  uri: string;
  bytes: number;
}

const ROOT = join(process.cwd(), ".data", "episodes");

const EXTENSIONS: Record<string, string> = {
  rgb: "webm",
  imu: "bin",
  audio: "webm",
};

export async function storeStream(
  episodeId: string,
  kind: string,
  bytes: Uint8Array,
): Promise<StoredStream> {
  // Episode ids are generated by the client; never let one escape the store.
  if (!/^ep_[0-9a-f]{8,64}$/.test(episodeId)) {
    throw new Error(`Refusing to store under a malformed episode id: ${episodeId}`);
  }
  if (!/^[a-z]{1,16}$/.test(kind)) {
    throw new Error(`Refusing to store a malformed stream kind: ${kind}`);
  }

  const dir = join(ROOT, episodeId);
  await mkdir(dir, { recursive: true });

  const name = `${kind}.${EXTENSIONS[kind] ?? "bin"}`;
  await writeFile(join(dir, name), bytes);

  return { kind, uri: `file://${join(dir, name)}`, bytes: bytes.byteLength };
}
