/**
 * Episode byte storage.
 *
 * Stands in for the content-addressed storage of product-spec §10.2 until a
 * provider is picked — the design keeps this behind one interface precisely so
 * that choice can wait. Files land under .data/episodes/<episode_id>/ where
 * they can be inspected, played and fed to the trainer without a gateway.
 */

import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

export interface StoredStream {
  kind: string;
  uri: string;
  bytes: number;
  /**
   * The container the bytes are actually in, taken from the sealed manifest.
   * An iPhone records MP4 and an Android WebM, so this cannot be assumed from
   * the stream kind — a buyer downloading an episode must be told the truth
   * about what they are receiving.
   */
  content_type?: string;
}

const ROOT = join(process.cwd(), ".data", "episodes");

/** By container, not by kind: Safari gives MP4 where Chromium gives WebM. */
const EXTENSIONS: Record<string, string> = {
  "video/webm": "webm",
  "video/mp4": "mp4",
  "audio/webm": "webm",
  "audio/mp4": "m4a",
  "application/octet-stream": "bin",
};

/** Strips the `;codecs=...` parameter, leaving the container's media type. */
export function baseContentType(
  contentType: string | undefined | null,
): string {
  return (contentType ?? "").split(";")[0].trim().toLowerCase();
}

export function extensionFor(contentType: string | undefined | null): string {
  return EXTENSIONS[baseContentType(contentType)] ?? "bin";
}

/**
 * The stored path for a stream, whatever container it landed in.
 *
 * Anything reading episodes off disk must go through this rather than assuming
 * `rgb.webm` — an iPhone's episode is `rgb.mp4`, and a hardcoded extension
 * silently skips it instead of failing.
 */
export function resolveStreamPath(
  episodeDir: string,
  kind: string,
): string | null {
  const candidates = [...new Set(Object.values(EXTENSIONS))];
  for (const ext of candidates) {
    const path = join(episodeDir, `${kind}.${ext}`);
    if (existsSync(path)) return path;
  }
  return null;
}

export async function storeStream(
  episodeId: string,
  kind: string,
  bytes: Uint8Array,
  contentType?: string,
): Promise<StoredStream> {
  // Episode ids are generated by the client; never let one escape the store.
  if (!/^ep_[0-9a-f]{8,64}$/.test(episodeId)) {
    throw new Error(
      `Refusing to store under a malformed episode id: ${episodeId}`,
    );
  }
  if (!/^[a-z]{1,16}$/.test(kind)) {
    throw new Error(`Refusing to store a malformed stream kind: ${kind}`);
  }

  const dir = join(ROOT, episodeId);
  await mkdir(dir, { recursive: true });

  const name = `${kind}.${extensionFor(contentType)}`;
  await writeFile(join(dir, name), bytes);

  return {
    kind,
    uri: `file://${join(dir, name)}`,
    bytes: bytes.byteLength,
    content_type: contentType,
  };
}

/**
 * Store an episode's aligned flow/gyro traces.
 *
 * Kept beside the streams rather than inside market.json: the store is read
 * and rewritten on every marketplace operation, and a hundred and sixty points
 * per episode would turn a small index into a large one for data only one
 * screen ever reads.
 */
export async function storeTraces(episodeId: string, traces: unknown): Promise<void> {
  if (!/^ep_[0-9a-f]{8,64}$/.test(episodeId)) {
    throw new Error(`Refusing to store under a malformed episode id: ${episodeId}`);
  }
  const dir = join(ROOT, episodeId);
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, "traces.json"), JSON.stringify(traces));
}

export async function readTraces(episodeId: string): Promise<unknown | null> {
  if (!/^ep_[0-9a-f]{8,64}$/.test(episodeId)) return null;
  const path = join(ROOT, episodeId, "traces.json");
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(await readFile(path, "utf8"));
  } catch {
    return null;
  }
}
